### ISSUE TITLE
(black screen, screen froze) crashing

### ISSUE THREAD

**Issue by snwchow** [Tildehat/EON-Class-Addition-Mod#1]
First of all thank you for spending time of putting these 2 classes in, they are pretty fun, really appreciate your dedication!

on to the issues: I am playing on a physical (old)3DS, I started a new game+ with a team of NS/Imp Alch/Sov Hero/WM L/Prot Buc/Gun from level1, everything was fine until ~Southern Shrine (?), which is when I encountered the first bug.  Load into the HQ for map/monster/item dex, then when I tried to go back to the town menu, I was greeted by a black screen and the town menu won't load...could still Zoom in and out with X, but black screen just won't go away and nothing would load.

Restarted and load the savefile, Inn and shop was working fine, but HQ is not(just going in to HQ without doing anything and then leaving would result in blackscreen)
Somehow got around by going into Map Selection screen, and then hop back into town without doing anything, then HQ worked fine...No idea how I got it working tbh.

Then after Southern Shrine, my Landsknecht would consistently crash(froze) the game by using Links, turn order is something like: Hero uses Mirage Sword, Alch uses Palm, Landy uses Link, NS uses Throw, Buc uses Chase; Link/Chase goes first, then the throw would hit, but once the "damage animation with number" ends, the game would froze...have to hard reset.  Also tried simply using Link and everyone else (regular)attack, the first attack that goes off after the link would freeze the game, at the end of the damage animation.

Then I kinda narrow down the issue, noticing game won't crash if I don't use Link, so I didn't...until I got to Undersea Grotto for that subclass (which I already have due to NG+, but never used it until this point), tried to go to the guild for a rest+reclass/reskills, the same Blackscreen problem happens just like HQ...maybe Muller isn't here in the Guild Area/Princess isn't at HQ that is a part of the problem?

Sometimes gathering materials at the world map and then going back to town(for Guild/HQ stuff) would be fine, where the blackscreen won't occur, but I could not find a consistent way of avoiding the blackscreen except for "not going into guild/HQ".

I've also tried using my previous team that has a Landy but no Alch/Buc, and the Link would work fine, so maybe something to do with Alch/Buc interaction.

The other not so crucial stuff:
Other then the blackscreen/freeze, most of the enemies' buff would show "Temp Buff Skill Message" instead, the buff name is still correct though...no biggie if I remember what every enemies' buff does.

Palm + Venom Formula wouldn't register "Killing with Bash" for some odd reason, and even though Palm would carry the element to the next (few turn), it would still sometimes ignore the (composite)weakness ie. Fire Palm + Riot on Alraune would deal minimum damage on hits that is not fire.

Also, when registering/choosing Buccaneer class from the guild, it would show the Farmer's description instead; while Alchemist shows Buccaneer's (Pirate related description)

That's all I've found as of now, sorry for the long block of text, I am a new github user and obviously not a tester/debugger, but simply a random guy who appreciate and enjoy this mod of yours.  Hopefully this "report" will be somehow helpful to you!

**Comment by Tildehat** [comment]
Thanks for playing the mod and alerting me of these bugs.

The blackscreen problem is strange. I haven't had it occur to me and can't replicate it. It might be a problem with an old SD card but I can't be certain.

Good catch on the crash with Links and Buccaneer. I've pinpointed it to Double Chase being the problem; this will be fixed in the next release. Same with the enemy buff text. That's a wrong placed file that will also be fixed.

The way Palms work is exactly like in EO2U. They replace your next move's element rather than adding to it. So using Fire Palm would make Venom Formula Fire element and not Fire + Bash.

The wrong text shown on Buccaneer and Alchemist during class creation is a known issue. Haven't pinpointed the problem yet but since it's a minor and non game breaking issue it's not a top priority.

**Comment by Tildehat** [comment]
Fixed up the issue with the black screen softlock in the newest release.

**Comment by snwchow** [comment]
I want to thank you for the lightning fast respond+fix (which I missed last time)!
I am assuming the newest black screen fix is regarding the issue that I've reported last time; is the bug something that can be easily explained or is it some weird complicated stuff at work?
Regardless, keep up the awesome work!

**Comment by Tildehat** [comment]
It had to do with the game attempting to call a file(in most cases a voice clip) that don't exist in the game files. For example the generic soldier when they're in the guild hall does this when switching parties.

**Comment by snwchow** [comment]
ah, so that's why it ended up always freezing when there are no voiceline played upon exiting, but no freeze if a voiceline is played. (even though this is just the result)
